require "test_helper"
require "paradem_pdf"
require "support/pdf_helpers"
require "support/cache_store"
require "support/rails_app"

class CacheTest < Minitest::Test
  include PdfHelpers

  def setup
    assert ParademPdf.const_defined?(:Cache, false), "The public byte cache is missing"
    @store = TestCacheStore.new
    @cache = ParademPdf::Cache.new(store: @store)
  end

  def inputs
    {"doc_type" => "invoice", "kind" => "footer", "namespace" => "app", "locale" => "en",
     "page" => 1, "total_pages" => 2, "html" => "footer", "assets_version" => "v1",
     "options" => {"margin" => {"bottom" => "15mm"}}, "render_version" => "1"}
  end

  def test_each_logical_dimension_changes_a_bounded_sha256_key
    key = @cache.key(inputs: inputs)
    assert_match(/\Aparadem_pdf\/[0-9a-f]{64}\z/, key)
    inputs.each_key do |field|
      changed = inputs.merge(field => "changed")
      refute_equal key, @cache.key(inputs: changed), field
    end
    refute_equal key, @cache.key(inputs: inputs.merge("options" => {"margin" => {"bottom" => "16mm"}}))
    assert_equal key, @cache.key(inputs: inputs.to_a.reverse.to_h)
    assert_operator @cache.key(inputs: {"namespace" => "x" * 100_000}).bytesize, :<, 100
  end

  def test_canonicalizes_nested_hashes_preserving_arrays_and_json_values
    first = {"z" => [{"b" => 2, "a" => 1}], "a" => [nil, true, false, 1.5]}
    second = {"a" => [nil, true, false, 1.5], "z" => [{"a" => 1, "b" => 2}]}
    assert_equal @cache.key(inputs: first), @cache.key(inputs: second)
    refute_equal @cache.key(inputs: first), @cache.key(inputs: first.merge("a" => first["a"].reverse))
    shared = ["repeated"]
    assert_kind_of String, @cache.key(inputs: [shared, shared])
  end

  def test_rejects_unsupported_values_nonfinite_floats_and_cycles
    cycle = []
    cycle << cycle
    hash_cycle = {}
    hash_cycle["self"] = hash_cycle
    [{symbol: "value"}, :symbol, Object.new, Time.now, Float::NAN, Float::INFINITY,
      -Float::INFINITY, cycle, hash_cycle, {"nested" => [Object.new]}].each do |value|
      assert_raises(ArgumentError) { @cache.key(inputs: value) }
    end
  end

  def test_requires_read_write_and_positive_finite_numeric_expiry
    assert_raises(ArgumentError) { ParademPdf::Cache.new(store: Object.new) }
    [nil, 0, -1, "60", Float::NAN, Float::INFINITY, Complex(1, 2)].each do |expiry|
      assert_raises(ArgumentError) { @cache.fetch(key: "key", expires_in: expiry) { flunk "Invalid expiry generated bytes" } }
    end
    assert_empty @store.reads
  end

  def test_stores_valid_bytes_hits_without_generation_and_forwards_expiry
    bytes = pdf_bytes("one")
    assert_equal bytes, @cache.fetch(key: "key", expires_in: 1.5) { bytes }
    assert_equal [["key", bytes, 1.5]], @store.writes
    assert_equal bytes, @cache.fetch(key: "key", expires_in: 1.5, require_cache_write: true) { flunk "Warm hit converted" }
    @store.now = 2
    new_bytes = pdf_bytes("two")
    assert_equal new_bytes, @cache.fetch(key: "key", expires_in: 1.5) { new_bytes }
  end

  def test_regenerates_corrupt_empty_non_string_and_wrong_page_count_hits
    [nil, "", "garbage", Object.new, pdf_bytes, pdf_bytes("one", "two"), page_pdf(MediaBox: [0, 0, 0, 792])].each do |bad|
      @store.entries["key"] = [bad, 60]
      bytes = pdf_bytes("valid")
      assert_equal bytes, @cache.fetch(key: "key", expires_in: 60, expected_pages: 1) { bytes }
    end
  end

  def test_invalid_generated_bytes_never_write
    [nil, "garbage", pdf_bytes, pdf_bytes("one", "two")].each do |bad|
      assert_raises(ParademPdf::InvalidPdf) { @cache.fetch(key: "key", expires_in: 60, expected_pages: 1) { bad } }
    end
    assert_empty @store.writes
  end

  def test_rejected_writes_are_best_effort_or_strict_and_exceptions_propagate
    bytes = pdf_bytes("valid")
    [false, nil].each do |rejection|
      @store.write_result = rejection
      assert_equal bytes, @cache.fetch(key: "key", expires_in: 60) { bytes }
      assert_raises(ParademPdf::CacheWriteFailed) { @cache.fetch(key: "key", expires_in: 60, require_cache_write: true) { bytes } }
    end
    failure = RuntimeError.new("store failed")
    @store.read_error = failure
    assert_same failure, assert_raises(RuntimeError) { @cache.fetch(key: "key", expires_in: 60) { bytes } }
    @store.read_error = nil
    @store.write_error = failure
    assert_same failure, assert_raises(RuntimeError) { @cache.fetch(key: "key", expires_in: 60) { bytes } }
  end

  def test_read_returns_bytes_on_hit_nil_on_miss_and_corrupt
    bytes = pdf_bytes("one")
    @store.entries["key"] = [bytes, 60]
    assert_equal bytes, @cache.read(key: "key")

    assert_nil @cache.read(key: "missing")

    @store.entries["key"] = ["garbage", 60]
    assert_nil @cache.read(key: "key")
  end

  def test_read_propagates_store_errors
    failure = RuntimeError.new("store failed")
    @store.read_error = failure
    assert_same failure, assert_raises(RuntimeError) { @cache.read(key: "key") }
  end

  def test_write_validates_bytes_before_writing
    [nil, "garbage", pdf_bytes, pdf_bytes("one", "two")].each do |bad|
      assert_raises(ParademPdf::InvalidPdf) { @cache.write(key: "key", bytes: bad, expires_in: 60, expected_pages: 1) }
    end
    assert_empty @store.writes
  end

  def test_write_is_best_effort_or_strict_and_propagates_errors
    bytes = pdf_bytes("valid")
    [false, nil].each do |rejection|
      @store.write_result = rejection
      assert_equal bytes, @cache.write(key: "key", bytes: bytes, expires_in: 60)
      assert_raises(ParademPdf::CacheWriteFailed) { @cache.write(key: "key", bytes: bytes, expires_in: 60, require_cache_write: true) }
    end
    failure = RuntimeError.new("store failed")
    @store.write_error = failure
    assert_same failure, assert_raises(RuntimeError) { @cache.write(key: "key", bytes: bytes, expires_in: 60) }
  end

  def test_write_validates_expiry
    [nil, 0, -1, "60", Float::NAN, Float::INFINITY, Complex(1, 2)].each do |expiry|
      assert_raises(ArgumentError) { @cache.write(key: "key", bytes: pdf_bytes("one"), expires_in: expiry) }
    end
    assert_empty @store.writes
  end
end

if ENV["PARADEM_PDF_RAILS_SUBPROCESS"] == "1"
  class CacheFileStoreTest < Minitest::Test
    include PdfHelpers

    def test_documents_share_completed_and_overlay_bytes_across_file_store_instances
      Dir.mktmpdir("paradem-pdf-cache-integration-") do |directory|
        first = ActiveSupport::Cache::FileStore.new(directory)
        second = ActiveSupport::Cache::FileStore.new(directory)
        options = {doc_type: "report", body_html: "body", origin: "https://reports.example.test/", locale: "en",
                   cache_namespace: "integration", freshness: "snapshot", assets_version: "assets", expires_in: 60,
                   footer: ->(page:, total_pages:) { "footer #{page}/#{total_pages}" }}
        conversions = []
        convert_using(->(_kind, html, *) {
          conversions << html
          pdf_bytes(html)
        }) do
          bytes = ParademPdf::Document.new(**options, cache: first).to_pdf(require_cache_write: true)
          assert_equal bytes, ParademPdf::Document.new(**options, cache: second).to_pdf(require_cache_write: true)
          other = ParademPdf::Document.new(**options.merge(body_html: "other", freshness: "other"), cache: second).to_pdf
          assert_includes page_text(ParademPdf::Document.parse_pdf(other).pages.first), "footer 1/1"
        end
        assert_equal ["body", "footer 1/1", "other"], conversions
      end
    end

    def test_file_store_expiry_regenerates_actual_document_and_overlay_entries
      Dir.mktmpdir("paradem-pdf-cache-expiry-") do |directory|
        store = ActiveSupport::Cache::FileStore.new(directory)
        options = {doc_type: "report", body_html: "body", origin: "https://reports.example.test/", locale: "en",
                   cache: store, cache_namespace: "integration", freshness: "snapshot", assets_version: "assets",
                   expires_in: 0.01, footer: ->(**) { "footer" }}
        conversions = []
        convert_using(->(_kind, html, *) {
          conversions << html
          pdf_bytes(html)
        }) do
          ParademPdf::Document.new(**options).to_pdf
          sleep 0.03
          ParademPdf::Document.new(**options).to_pdf
        end
        assert_equal ["body", "footer", "body", "footer"], conversions
      end
    end
  end
else
  class CacheFileStoreSubprocessTest < Minitest::Test
    include RailsSubprocess

    def test_actual_documents_with_optional_file_store_integration
      run_rails_test(__FILE__)
    end
  end
end
